### ISSUE TITLE
Pre launch tweaks

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/optf-website#1]
All issues reported on Chrome desktop 1920x1080

1. Spacing on home page is inconsistent with live website, we should increase the size of the logos and decrease the vertical space of the blue gradient div to provide subtle indication that user can scroll. 

Original site 
![image](https://user-images.githubusercontent.com/27277414/233522532-01557e84-4c30-4a9d-a7cf-53ad161cdb91.png)

New site 
![image](https://user-images.githubusercontent.com/27277414/233522637-b7dab31a-3786-438c-ac11-e65221780a62.png)

2. Menu buttons font and color should be made more prominent, copy original 

Original site 

![image](https://user-images.githubusercontent.com/27277414/233522933-7541b77c-8421-455c-9c49-dc08491402ec.png)

New site

![image](https://user-images.githubusercontent.com/27277414/233522970-3aa95153-9d54-48df-93c3-36ff3dd2718e.png)

3. OPTF logo being squashed 

Original site 
![image](https://user-images.githubusercontent.com/27277414/233523087-382c546e-91b4-419d-8e13-ec480786ac0b.png)

New site 

![image](https://user-images.githubusercontent.com/27277414/233523154-a57b1370-a7b0-40fc-af48-8422c463589d.png)

4. Visual inconsistency with dotted line seperators 

Original site 

![image](https://user-images.githubusercontent.com/27277414/233523320-19092ae2-9f3a-499c-886a-e3381a7824bf.png)

New site 

![image](https://user-images.githubusercontent.com/27277414/233523354-9e3ad928-2943-4813-8d56-821a818bb373.png)

5. Use less horizontal space on projects page, makes boxes look more empty 

Original site 

![image](https://user-images.githubusercontent.com/27277414/233523575-d68926a4-ee5e-49e9-9463-e41fc4ac582a.png)

New site 

![image](https://user-images.githubusercontent.com/27277414/233523635-72b8f2fe-4671-46c6-947a-e1980c55f514.png)

6. Change research page, PDF viewer to use whole page view by default 

Original site 

![image](https://user-images.githubusercontent.com/27277414/233524057-4bc3dbca-6345-4da4-bc45-f4fffc7fb435.png)

New Site 

![image](https://user-images.githubusercontent.com/27277414/233524012-213e6890-669d-42fc-94f8-4149508f64ff.png)

7. Hyperlink logos to relevant projects on about page

![image](https://user-images.githubusercontent.com/27277414/233524181-7e644a86-8939-462c-88fb-fd30f632c469.png)

8. Make sure we change this before launch

![image](https://user-images.githubusercontent.com/27277414/233524397-f24240fc-06cd-4322-be1e-835af03a53f9.png)

There also seems to be some missing information on the about page, but ill ping you about that

**Comment by tomobre** [comment]
> 5. Use less horizontal space on projects page, makes boxes look more empty

It seems like this happens only on XL screen, In this case, do you want me to make the font bigger to take more space on the left box?  Or what did you mean by 'use less horizontal space'?

**Comment by KeeJef** [comment]
> > 5. Use less horizontal space on projects page, makes boxes look more empty
> 
> It seems like this happens only on XL screen, In this case, do you want me to make the font bigger to take more space on the left box? Or what did you mean by 'use less horizontal space'?

Constrain the max box width at 450px or something like that otherwise the box will expand and look emptier as the viewport grows

**Comment by tomobre** [comment]
the issues are fixed now  @KeeJef , except for this one:

> There also seems to be some missing information on the about page, but ill ping you about that

**Comment by KeeJef** [comment]
Resolved
